In [1]:
# importing pandas
import pandas as pd

In [2]:
df=pd.read_csv("test.csv")

In [3]:
df

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [4]:
# to see what datatype are there
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    str
 3   Sex          418 non-null    str
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    str
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     str
 10  Embarked     418 non-null    str
dtypes: float64(2), int64(4), str(5)
memory usage: 36.1 KB

In [5]:
# finding Duplicate value
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
413    False
414    False
415    False
416    False
417    False
Length: 418, dtype: bool

In [6]:
# it shows how many duplicate values are there
df.duplicated().sum()

np.int64(0)

In [7]:
# column names
df.columns

Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [55]:
# checking balance
print(df['Age'].skew())

0.4573612871503845

In [49]:
# Store column names in column variable
columns=['PassengerId', 'Pclass','Age', 'SibSp', 'Parch',
        'Fare']

In [63]:
# printing all column skew values
for i in columns:
    print(df[i].skew())

0.0
-0.5341703482345055
0.6607470412147504
4.168336568562722
4.654461698299236
3.6872133081121405

In [8]:
# Displaying null values
df.isnull()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...
413,False,False,False,False,True,False,False,False,False,True,False
414,False,False,False,False,False,False,False,False,False,False,False
415,False,False,False,False,False,False,False,False,False,True,False
416,False,False,False,False,True,False,False,False,False,True,False
417,False,False,False,False,True,False,False,False,False,True,False

In [9]:
# how many null in columns
df.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [21]:
# Filling median values in missing values
df['Age']=df['Age'].fillna(df['Age'].median())

In [ ]:
df.drop("Cabin",axis=1,inplace=True)

In [27]:
df.isnull().sum()

PassengerId    0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           1
Embarked       0
dtype: int64

In [28]:
df['Fare']=df['Fare'].fillna(df['Fare'].median())

In [29]:
# Checking null values in column
df.isnull().sum()

PassengerId    0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [31]:
# detecting Outlayers And fix
columns = df.select_dtypes(include=['int64','float64']).columns

for col in columns:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]
    print(f"{col} outliers count:", len(outliers))

    df[col] = df[col].clip(lower, upper)

PassengerId outliers count: 0
Pclass outliers count: 0
Age outliers count: 36
SibSp outliers count: 11
Parch outliers count: 94
Fare outliers count: 55

In [32]:
# if you have a duplicate values use this code
df.drop_duplicates()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,892,3,"Kelly, Mr. James",male,34.500,0.0,0,330911,7.829200,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.000,1.0,0,363272,7.000000,S
2,894,2,"Myles, Mr. Thomas Francis",male,54.875,0.0,0,240276,9.687500,Q
3,895,3,"Wirz, Mr. Albert",male,27.000,0.0,0,315154,8.662500,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.000,1.0,0,3101298,12.287500,S
...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,27.000,0.0,0,A.5. 3236,8.050000,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.000,0.0,0,PC 17758,66.835988,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.500,0.0,0,SOTON/O.Q. 3101262,7.250000,S
416,1308,3,"Ware, Mr. Frederick",male,27.000,0.0,0,359309,8.050000,S
417,1309,3,"Peter, Master. Michael J",male,27.000,1.0,0,2668,22.358300,C

In [33]:
df.isnull().sum()

PassengerId    0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [35]:
df.drop('Sex',axis=1)

,PassengerId,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Embarked
0,892,3,"Kelly, Mr. James",34.500,0.0,0,330911,7.829200,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",47.000,1.0,0,363272,7.000000,S
2,894,2,"Myles, Mr. Thomas Francis",54.875,0.0,0,240276,9.687500,Q
3,895,3,"Wirz, Mr. Albert",27.000,0.0,0,315154,8.662500,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",22.000,1.0,0,3101298,12.287500,S
...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",27.000,0.0,0,A.5. 3236,8.050000,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",39.000,0.0,0,PC 17758,66.835988,C
415,1307,3,"Saether, Mr. Simon Sivertsen",38.500,0.0,0,SOTON/O.Q. 3101262,7.250000,S
416,1308,3,"Ware, Mr. Frederick",27.000,0.0,0,359309,8.050000,S
417,1309,3,"Peter, Master. Michael J",27.000,1.0,0,2668,22.358300,C

In [38]:
# droping pernmently
df.drop('Sex',axis=1,inplace=True)

In [39]:
df

,PassengerId,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Embarked
0,892,3,"Kelly, Mr. James",34.500,0.0,0,330911,7.829200,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",47.000,1.0,0,363272,7.000000,S
2,894,2,"Myles, Mr. Thomas Francis",54.875,0.0,0,240276,9.687500,Q
3,895,3,"Wirz, Mr. Albert",27.000,0.0,0,315154,8.662500,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",22.000,1.0,0,3101298,12.287500,S
...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",27.000,0.0,0,A.5. 3236,8.050000,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",39.000,0.0,0,PC 17758,66.835988,C
415,1307,3,"Saether, Mr. Simon Sivertsen",38.500,0.0,0,SOTON/O.Q. 3101262,7.250000,S
416,1308,3,"Ware, Mr. Frederick",27.000,0.0,0,359309,8.050000,S
417,1309,3,"Peter, Master. Michael J",27.000,1.0,0,2668,22.358300,C

In [40]:
df.rename(columns={'Name':'peru'})

,PassengerId,Pclass,peru,Age,SibSp,Parch,Ticket,Fare,Embarked
0,892,3,"Kelly, Mr. James",34.500,0.0,0,330911,7.829200,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",47.000,1.0,0,363272,7.000000,S
2,894,2,"Myles, Mr. Thomas Francis",54.875,0.0,0,240276,9.687500,Q
3,895,3,"Wirz, Mr. Albert",27.000,0.0,0,315154,8.662500,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",22.000,1.0,0,3101298,12.287500,S
...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",27.000,0.0,0,A.5. 3236,8.050000,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",39.000,0.0,0,PC 17758,66.835988,C
415,1307,3,"Saether, Mr. Simon Sivertsen",38.500,0.0,0,SOTON/O.Q. 3101262,7.250000,S
416,1308,3,"Ware, Mr. Frederick",27.000,0.0,0,359309,8.050000,S
417,1309,3,"Peter, Master. Michael J",27.000,1.0,0,2668,22.358300,C

In [41]:
df.rename(columns={'peru':'name'},inplace=True)

In [42]:
df

,PassengerId,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Embarked
0,892,3,"Kelly, Mr. James",34.500,0.0,0,330911,7.829200,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",47.000,1.0,0,363272,7.000000,S
2,894,2,"Myles, Mr. Thomas Francis",54.875,0.0,0,240276,9.687500,Q
3,895,3,"Wirz, Mr. Albert",27.000,0.0,0,315154,8.662500,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",22.000,1.0,0,3101298,12.287500,S
...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",27.000,0.0,0,A.5. 3236,8.050000,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",39.000,0.0,0,PC 17758,66.835988,C
415,1307,3,"Saether, Mr. Simon Sivertsen",38.500,0.0,0,SOTON/O.Q. 3101262,7.250000,S
416,1308,3,"Ware, Mr. Frederick",27.000,0.0,0,359309,8.050000,S
417,1309,3,"Peter, Master. Michael J",27.000,1.0,0,2668,22.358300,C

In [43]:
df.drop_duplicates()

,PassengerId,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Embarked
0,892,3,"Kelly, Mr. James",34.500,0.0,0,330911,7.829200,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",47.000,1.0,0,363272,7.000000,S
2,894,2,"Myles, Mr. Thomas Francis",54.875,0.0,0,240276,9.687500,Q
3,895,3,"Wirz, Mr. Albert",27.000,0.0,0,315154,8.662500,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",22.000,1.0,0,3101298,12.287500,S
...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",27.000,0.0,0,A.5. 3236,8.050000,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",39.000,0.0,0,PC 17758,66.835988,C
415,1307,3,"Saether, Mr. Simon Sivertsen",38.500,0.0,0,SOTON/O.Q. 3101262,7.250000,S
416,1308,3,"Ware, Mr. Frederick",27.000,0.0,0,359309,8.050000,S
417,1309,3,"Peter, Master. Michael J",27.000,1.0,0,2668,22.358300,C

In [45]:
df.sort_values(by='Pclass',ascending=True)

,PassengerId,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Embarked
20,912,1,"Rothschild, Mr. Martin",54.875,1.0,0,PC 17603,59.400000,C
22,914,1,"Flegenheim, Mrs. Alfred (Antoinette)",27.000,0.0,0,PC 17598,31.683300,S
23,915,1,"Williams, Mr. Richard Norris II",21.000,0.0,0,PC 17597,61.379200,C
24,916,1,"Ryerson, Mrs. Arthur Larned (Emily Maria Borie)",48.000,1.0,0,PC 17608,66.835988,C
28,920,1,"Brady, Mr. John Bertram",41.000,0.0,0,113054,30.500000,S
...,...,...,...,...,...,...,...,...,...
19,911,3,"Assaf Khalil, Mrs. Mariana (Miriam"")""",45.000,0.0,0,2696,7.225000,C
18,910,3,"Ilmakangas, Miss. Ida Livija",27.000,1.0,0,STON/O2. 3101270,7.925000,S
17,909,3,"Assaf, Mr. Gerios",21.000,0.0,0,2692,7.225000,C
417,1309,3,"Peter, Master. Michael J",27.000,1.0,0,2668,22.358300,C
0,892,3,"Kelly, Mr. James",34.500,0.0,0,330911,7.829200,Q